language: node_js
node_js: "12"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: "f591fb83-a1c2-4adc-b60e-d91ed962b0c3"
  app: team-task-management-system
